### PR TITLE
Added support netstandard.

### PR DESCRIPTION
**Pull request by FoxTes**
I thought it would be better to add netstandard. Thus, there will be versatility. Please see.

By the way, my last PR broke Github Action.

### CODE REVIEW

**Comment by sefacan** [comment]
@FoxTes we don't need dotnet standard anymore. We should add multi target for dotnet 5 and dotnet 6.

**Comment by FoxTes** [comment]
And why? I would like to hear the reason.

netstandard 2.1 support only .NET и .NET Core | 3,0, 3,1, 5,0, 6,0

**Comment by FoxTes** [comment]
Returned the changes. Added net 6 support.

**Comment by FoxTes** [comment]
@sefacan Good afternoon. Do you see the PR?

**Pull request closed without merging**
